"""Stored bundle definitions — input tuples persisted as YAML.

A bundle definition pins everything the resolver needs: product, jurisdictions,
standards, and the module names to compose. Storing the tuple in a versioned
file is what enables the `regenerate` workflow: re-running the resolver on the
same definition after the modules or registry have moved produces a diff that
Git tracks.

Files live at ``bundles/<name>.yaml`` by convention. The companion matrix
output (``bundles/<name>.matrix.json``) is generated by ``openqms regenerate``
and is also typically Git-tracked — its diff is the regulatory audit trail of
how the scope and artifacts co-evolved.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import yaml

from .types import Bundle


@dataclass(frozen=True)
class BundleDef:
    """A stored bundle definition: input tuple plus the module names to load."""

    name: str
    bundle: Bundle
    modules: tuple[str, ...]


def load_bundle_def(path: Path | str) -> BundleDef:
    """Load a bundle definition from a YAML file.

    Required top-level keys: ``name`` (str), ``product`` (str), ``modules``
    (list[str]). Optional keys: ``jurisdictions`` (list[str], default empty),
    ``standards`` (list[str], default empty).
    """
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"Bundle definition not found: {p}")

    data = yaml.safe_load(p.read_text()) or {}

    name = data.get("name")
    if not name:
        raise ValueError(f"Bundle definition at {p} missing required 'name'")

    product = data.get("product")
    if not product:
        raise ValueError(
            f"Bundle definition {name!r} missing required 'product'"
        )

    jurisdictions = data.get("jurisdictions") or []
    standards = data.get("standards") or []
    modules = data.get("modules") or []

    for field, val in (
        ("jurisdictions", jurisdictions),
        ("standards", standards),
        ("modules", modules),
    ):
        if not isinstance(val, list):
            raise ValueError(
                f"Bundle definition {name!r}: '{field}' must be a list"
            )

    if not modules:
        raise ValueError(
            f"Bundle definition {name!r} must list at least one module"
        )

    return BundleDef(
        name=str(name),
        bundle=Bundle(
            product=str(product),
            jurisdictions=tuple(str(j) for j in jurisdictions),
            standards=tuple(str(s) for s in standards),
        ),
        modules=tuple(str(m) for m in modules),
    )
